# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 11:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170705_0559'),
        ('impersonate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonateUser',
            fields=[
            ],
            options={
                'verbose_name': 'Impersonate User',
                'verbose_name_plural': 'Impersonate User',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='impersonationlog',
            options={'verbose_name': 'Impersonation Log', 'verbose_name_plural': 'Impersonation Logs'},
        ),
        migrations.AlterField(
            model_name='impersonationlog',
            name='impersonating',
            field=models.ForeignKey(help_text='The user being impersonated.', on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_by', to=settings.AUTH_USER_MODEL, verbose_name='Impersonating'),
        ),
        migrations.AlterField(
            model_name='impersonationlog',
            name='impersonator',
            field=models.ForeignKey(help_text='The user doing the impersonating.', on_delete=django.db.models.deletion.CASCADE, related_name='impersonations', to=settings.AUTH_USER_MODEL, verbose_name='Impersonator'),
        ),
        migrations.AlterField(
            model_name='impersonationlog',
            name='session_ended_at',
            field=models.DateTimeField(blank=True, help_text='The time impersonation ended.', null=True, verbose_name='Session Ended At'),
        ),
        migrations.AlterField(
            model_name='impersonationlog',
            name='session_key',
            field=models.CharField(help_text='The Django session request key.', max_length=40, verbose_name='Session Key'),
        ),
        migrations.AlterField(
            model_name='impersonationlog',
            name='session_started_at',
            field=models.DateTimeField(blank=True, help_text='The time impersonation began.', null=True, verbose_name='Session Started At'),
        ),
    ]
