# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 13:06
from __future__ import unicode_literals

from django.db import migrations


def fix_permissions(*args, **kwargs):
    from impersonate.management.commands import fix_permissions
    fix_permissions.Command().handle()


class Migration(migrations.Migration):

    dependencies = [
        ('impersonate', '0002_auto_20170705_1134'),
    ]

    operations = [
        migrations.RunPython(code=fix_permissions, reverse_code=lambda *args, **kwargs0: None)
    ]
